package resources;

import Entities.Question;

/**
 * Created by mathiaslarsen on 21/11/2016.
 */

public class DISC_Data {

    public static final int [] QuestionNo_DATA = {

            1,2,3,4,5,6,7,8,9,10,11,12,13,
            14,15,16,17,18,19,20,21,22,23,
            24,25,26,27,28,29,30,31,32,33,
            34,35,36,37,38,39,40,41,42,43,
            44,45,46,47,48,49,50,51,52,53,
            54,55,56,57,58,59,60,61,62,63,
            64,65,66,67,68,69,70,71,72

    };

    public static final String [] DISCWord_Data = {

            "Har mine egne meninger.",
            "Søger ofte accept fra andre.",
            "Jeg går lige til sagen.",
            "Undviger konfrontationer.",
            "Selvstændig og egenrådig.",
            "Søger samarbejde med andre.",
            "Fokuseret på egne idéer.",
            "Opmærksom på andres idéer og tanker.",
            "Træffer egne beslutninger.",
            "Lytter til andre.",
            "Sætter mål og arbejder efter dem.",
            "Arbejder efter fælles mål.",
            "Sagsorienteret.",
            "Giver dig god tid sammen med andre.",
            "Tager styringen.",
            "Arbejder gerne i grupper.",
            "Kontrollerer situationen.",
            "Tilpasser dig til situationen.",
            "Beslutter sig på baggrund af facts.",
            "Beslutter sig med ”mavefornemmelser.",
            "Direkte.",
            "Afventende.",
            "Skal overbevises.",
            "Forstående.",
            "Vil have tingene gjort nu.",
            "Arbejder støt og stabilt.",
            "Tænker logisk.",
            "Tænker abstrakt.",
            "Stædig.",
            "Undvigende.",
            "Påtrængende.",
            "Afslappet.",
            "Påpegende.",
            "Eftergivende.",
            "Bestemmende.",
            "Hensynsfuld.",
            "Egoistisk.",
            "Ydmyg.",
            "Impulsiv.",
            "Overvejende.",
            "Eksperimenterer.",
            "Søger det sikre.",
            "Generaliserende.",
            "Synes at detaljer er vigtige.",
            "Talende.",
            "Lyttende.",
            "Arbejder frit.",
            "Arbejder systematisk.",
            "Risikovillig.",
            "Sikkerhedssøgende.",
            "Tænker kreativt.",
            "Tænker analytisk.",
            "Meget social.",
            "Mindre social.",
            "Igangsætter konstant nye projekter.",
            "Er organiseret – følger helst en plan.",
            "Aktiv og igangsættende.",
            "Pligtopfyldende og stabil.",
            "Ligefrem.",
            "Tilbageholdende.",
            "Søger samarbejde med andre.",
            "Arbejder gerne alene.",
            "Hurtig til at konkludere.",
            "Tænker før der bliver talt.",
            "Dramatiserende.",
            "Entydig og saglig.",
            "Åben i samvær med nye mennesker.",
            "Reserveret i samvær med nye mennesker.",
            "Tænker abstrakt.",
            "Tænker konkret.",
            "Viser følelser.",
            "Holder følelser for dig selv.",

};
    public static final Question.questionType[] DISCTYPE_Data = {
                        Question.questionType.Dom,
                        Question.questionType.Sta,
                        Question.questionType.Dom,
                        Question.questionType.Sta,
                        Question.questionType.Dom,
                        Question.questionType.Sta,
                        Question.questionType.Dom,
                        Question.questionType.Sta,
                        Question.questionType.Dom,
                        Question.questionType.Sta,
                        Question.questionType.Dom,
                        Question.questionType.Sta,
                        Question.questionType.Dom,
                        Question.questionType.Sta,
                        Question.questionType.Dom,
                        Question.questionType.Sta,
                        Question.questionType.Dom,
                        Question.questionType.Sta,
                        Question.questionType.Dom,
                        Question.questionType.Sta,
                        Question.questionType.Dom,
                        Question.questionType.Sta,
                        Question.questionType.Dom,
                        Question.questionType.Sta,
                        Question.questionType.Dom,
                        Question.questionType.Sta,
                        Question.questionType.Dom,
                        Question.questionType.Sta,
                        Question.questionType.Dom,
                        Question.questionType.Sta,
                        Question.questionType.Dom,
                        Question.questionType.Sta,
                        Question.questionType.Dom,
                        Question.questionType.Sta,
                        Question.questionType.Dom,
                        Question.questionType.Sta,
                        Question.questionType.Inf,
                        Question.questionType.Com,
                        Question.questionType.Inf,
                        Question.questionType.Com,
                        Question.questionType.Inf,
                        Question.questionType.Com,
                        Question.questionType.Inf,
                        Question.questionType.Com,
                        Question.questionType.Inf,
                        Question.questionType.Com,
                        Question.questionType.Inf,
                        Question.questionType.Com,
                        Question.questionType.Inf,
                        Question.questionType.Com,
                        Question.questionType.Inf,
                        Question.questionType.Com,
                        Question.questionType.Inf,
                        Question.questionType.Com,
                        Question.questionType.Inf,
                        Question.questionType.Com,
                        Question.questionType.Inf,
                        Question.questionType.Com,
                        Question.questionType.Inf,
                        Question.questionType.Com,
                        Question.questionType.Inf,
                        Question.questionType.Com,
                        Question.questionType.Inf,
                        Question.questionType.Com,
                        Question.questionType.Inf,
                        Question.questionType.Com,
                        Question.questionType.Inf,
                        Question.questionType.Com,
                        Question.questionType.Inf,
                        Question.questionType.Com,
                        Question.questionType.Inf,
                        Question.questionType.Com




    };

}
